spring:
  application:
    name: jbone-bpm-server
  redis:
    host: 127.0.0.1
    port: 6379
    password: jbone
  #rabbitmq配置
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  thymeleaf:
    cache: false
    enabled: true
  freemarker:
    enabled: false
  jpa:
    show-sql: true
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/jbone_bpm?useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=TRUE&useSSL=false
    username: jbone_bpm
    password: Jbone_bpm_666

#服务
server:
  port: 60001

#注册中心
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:10001/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}

management:
  security:
    enabled: false

#Jbone配置
jbone:
  #当前系统名，在系统管理里面对应的名字
  sys:
    serverName: jbone-bpm-server
#    jdbc:
#      url: jdbc:mysql://127.0.0.1:3306/jbone_bpm?useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=TRUE
#      username: jbone_bpm
#      password: Jbone_bpm_666
#      driverClassName: com.mysql.jdbc.Driver
#      maxActive: 10
#      initialSize: 2
#      maxWait: 10000
  #系统管理Feign调用配置
  rpc.sysServer.feign:
    protocol: http
    name: jbone-sys-server

# info接口返回值
info:
  app:
    name: ${spring.application.name}
    version: 1.0.0
  java:
    version: ${java.version}
  code:
    git: https://github.com/417511458/jbone
    gitee: https://gitee.com/majunwei2017/jbone
  domain: http://www.majunwei.com

