-- MySQL Script generated by MySQL Workbench
-- Thu Mar 15 16:52:06 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema jbone_tag
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema jbone_tag
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `jbone_tag` DEFAULT CHARACTER SET utf8 ;
USE `jbone_tag` ;

-- -----------------------------------------------------
-- Table `jbone_tag`.`tag_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jbone_tag`.`tag_info` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '物理主键ID',
  `tag_id` VARCHAR(100) NOT NULL COMMENT '唯一键索引,通过ID生成工具生成',
  `name` VARCHAR(100) CHARACTER SET 'utf8mb4' NOT NULL COMMENT '标签名',
  `target` INT NOT NULL COMMENT '作用域。有限枚举，一旦新增，不能修改\n1-店铺\n2-商品\n3-CMS文章\n4-CMS专题\n5-CMS栏目',
  `status` INT NOT NULL COMMENT '状态。\n0：删除\n1：正常',
  `show` INT NOT NULL COMMENT '是否前台展示。一旦新增，不能修改\n0：不展示\n1：展示',
  `icon` VARCHAR(200) NULL COMMENT '标签图标',
  `icon_type` INT NULL COMMENT 'icon类型，如果设置为2，则展示图片，否则展示加CSS图片的name\n1：CSS图标\n2：图片',
  `click_target` VARCHAR(200) NOT NULL COMMENT '点击后的跳转链接，如jbone-cms.majunwei.com/topic/111',
  `time_validity` INT NOT NULL COMMENT '是否设置标签有效期。一旦新增，不能修改\n0：不设置有效期\n1：设置有效期',
  `start_time` TIMESTAMP NULL COMMENT '当设置”time_validity”为1时，该值必填。有效期的开始时间。',
  `end_time` TIMESTAMP NULL COMMENT '当设置”time_validity”为1时，该值必填。有效期的结束时间。',
  `extend` VARCHAR(2048) NULL COMMENT '预留扩展信息,json格式',
  `applier` VARCHAR(100) NULL COMMENT '申请人',
  `apply_reason` VARCHAR(200) NULL COMMENT '申请说明',
  `add_time` TIMESTAMP NULL COMMENT '记录添加时间',
  `update_time` TIMESTAMP NULL COMMENT '记录最后一次修改时间',
  `version` BIGINT NULL COMMENT '版本号，乐观锁',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `tag_id_UNIQUE` (`tag_id` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
